<a href="https://colab.research.google.com/github/vivekpenuli/Ml_class/blob/main/Residual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Step of finidng intercept and slope **


1.   Find the inital value of intercept ans slope using the formul.
2.   once the inital value is derived your inital inercept and slope
3. now you can use performance algo to improve the slope and intercept .



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df= pd.read_csv("https://raw.githubusercontent.com/vivekpenuli/Ml_class/main/Salary_Data.csv")

In [3]:
df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [4]:
x=df.iloc[:,:-1].values

In [5]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [6]:
y= df.iloc[:,-1]

In [7]:
y

0      39343
1      46205
2      37731
3      43525
4      39891
5      56642
6      60150
7      54445
8      64445
9      57189
10     63218
11     55794
12     56957
13     57081
14     61111
15     67938
16     66029
17     83088
18     81363
19     93940
20     91738
21     98273
22    101302
23    113812
24    109431
25    105582
26    116969
27    112635
28    122391
29    121872
Name: Salary, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train ,x_test ,y_train ,y_test = train_test_split(x,y,test_size=0.2,random_state=75)

In [10]:
x_train.shape

(24, 1)

In [11]:
y_train.shape

(24,)

In [12]:
x_test.shape

(6, 1)

In [13]:
y_test.shape

(6,)

Linear Regression

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
reg = LinearRegression()

In [16]:
reg.fit(x_train,y_train)

LinearRegression()

In [17]:
y_pre=reg.predict(x_test)

In [18]:
y_pre

array([ 71804.8541238 ,  43567.97132202,  36752.17202503, 101015.42253944,
        52331.14184671, 117568.07797497])

In [19]:
y_test

15     67938
3      43525
1      46205
22    101302
5      56642
27    112635
Name: Salary, dtype: int64

finidng slope and intercept

In [21]:
reg.intercept_

24094.259044924547

In [22]:
reg.coef_

array([9736.85613855])

finding means Absolute error

In [23]:
from sklearn.metrics import r2_score

In [24]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error


In [26]:
mean_absolute_error(y_test,y_pre)

3815.5278349337023

finding mean square error

In [27]:
mean_squared_error(y_test,y_pre)

24551874.506559536

Finding realtion between independent and dependent varaible

In [28]:
r2_score(y_test,y_pre)

0.9652242905568412